version: '3.9'

services:
  shobshop_db:
    image: postgres:14.3
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pgadmin
      POSTGRES_DB: shobshop_db
    volumes:
      - shobShopVol:/var/lib/postgresql/data
    networks:
      - shobShopNet

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - shobshop_db
    restart: always
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - shobShopPgVol:/var/lib/pgadmin
    networks:
      - shobShopNet

volumes:
  shobShopVol:
  shobShopPgVol:

networks:
  shobShopNet:
